### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by vcai01** [vcai01/know_before_you_go#1]
**A - Finding accommodation / short term / Airbnb**
**Part 1**
1. Business Understanding
- [x] Determine objectives
- [x] Produce a project plan
- [x] Define questions / hypothesize solutions

2. Data Understanding (EDA)
- [x] Collect initial data
- [x] Describe data
- [x] Verify data quality

3. Data Preparation
- [x] Select data
- [x] Construct new data
- [x] Clean data
- [ ] Integrate data*

**Part 2**
4. Modeling
- [ ] Engineer features
- [ ] Create models
- [ ] Validate models
- [ ] Select models

5. Evaluation
- [ ]  Measure efficacy

6. Deployment
- [ ]  Deploy solution
- [ ]  Produce a final report
